#!/bin/sh
# vsftpd auto docker in debian
# Powered by cr: zhangchaoren@openeasy.net

# db_load -T -t hash -f /etc/vsftpd/user.list /etc/vsftpd/user.db

WORK_DIR=$(pwd)
VERSION=debian-jessie

docker build -t vsftpd:$VERSION $WORK_DIR
