#!/bin/sh
# Nginx auto docker in debian
# Powered by cr: zhangchaoren@openeasy.net

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

WORK_DIR=$(pwd)
VERSION=xe-11.2.0
ORACLE_XE_FILE=oracle-xe-11.2.0-1.0.x86_64.rpm

if [ ! -s $ORACLE_XE_FILE.zip ]; then
    echo "$ORACLE_XE_FILE.zip not found in path $WORK_DIR."
    exit 1
fi

# 检查运行期间需要的工具是否安装
which unzip > /dev/null && which alien > /dev/null \
|| sudo apt-get update
which unzip > /dev/null && which alien > /dev/null \
|| sudo apt-get install -y unzip alien

unzip $ORACLE_XE_FILE
sudo alien -c Disk1/oracle-xe-11.2.0-1.0.x86_64.rpm

docker build -t oracle:$VERSION $WORK_DIR
