#!/bin/sh
# Nginx auto docker
# Powered by cr: zhangchaoren@openeasy.net


PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

echo "Please input nginx version:"
read -p "(Default version: 1.8.0):" VERSION
if [ "$VERSION" = "" ]; then
  VERSION=1.8.0
fi

WORKDIR=$(pwd)
PREFIX=$WORKDIR/nginx
NGINX_FILE=nginx-$VERSION.tar.gz
NGINX_URL=http://nginx.org/download/$NGINX_FILE

if [ -s $NGINX_FILE ]; then
    echo "tar zxvf $NGINX_FILE"
  else
    wget -c $NGINX_URL
fi

apt-get install -y gcc g++ make patch libpcre3-dev zlib1g-dev libssl-dev google-perftools/stable libgoogle-perftools-dev/stable

tar zxvf $NGINX_FILE
cd nginx-$VERSION

./configure --prefix=$PREFIX \
--sbin-path=$PREFIX/sbin/nginx \
--conf-path=$PREFIX/etc/nginx/nginx.conf \
--error-log-path=/var/log/nginx/error.log \
--http-log-path=/var/log/nginx/access.log \
--pid-path=/var/run/nginx.pid \
--lock-path=/var/lock/nginx.lock \
--http-client-body-temp-path=/var/cache/nginx/client_temp \
--http-proxy-temp-path=/var/cache/nginx/proxy_temp \
--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
--http-scgi-temp-path=/var/cache/nginx/scgi_temp \
--user=www --group=www \
--with-http_ssl_module \
--with-http_realip_module \
--with-http_addition_module \
--with-http_sub_module \
--with-http_dav_module \
--with-http_flv_module \
--with-http_mp4_module \
--with-http_gzip_static_module \
--with-http_random_index_module \
--with-http_secure_link_module \
--with-http_stub_status_module \
--with-mail \
--with-mail_ssl_module \
--with-file-aio \
--with-ipv6 \
--with-threads \
--with-google_perftools_module \
--with-cpp_test_module \
--with-cc-opt='-O2 -g -m64 -mtune=generic'

make
make install

docker build -t nginx:$VERSION $WORKDIR
