#!/bin/sh
# POST-COMMIT HOOK

REPOS=$1
TXN=$2
SVNLOOK=/usr/bin/svnlook

LOGMSG=$($SVNLOOK log -t "$TXN" "$REPOS" | grep "[a-zA-Z0-9]" | wc -c)
if [ "$LOGMSG" -lt 8 ]
then
    echo "\nPlease enter the message, for example:\n    1. Add modify and delete which files.\n    2. Modification increases the removal of what function.\n\n" 1>&2
    exit 1
fi
